### ISSUE TITLE
Required fields should be optional

### ISSUE THREAD

**Issue by vontell** [instabase/foundation#12]
All fields should be optional - this allows better forwards/backwards compatibility if a field needs to be deprecated later.

**Comment by vontell** [comment]
Lets look into this more, what is the right approach?

**Comment by andrey-ib** [comment]
Hmm. I personally prefer required + people lock their code to specific versions of backing libs, compared to optional + best-effort to be version compatible.

**Comment by vontell** [comment]
@andrey-ib can we debate this some more? 
https://stackoverflow.com/a/31814967/4061273
https://capnproto.org/faq.html#how-do-i-make-a-field-required-like-in-protocol-buffers
The standard approach here at the company has been along the lines of the optional camp

**Comment by andrey-ib** [comment]
Hmm, we can discuss in our 1-1. I think a lot of this is too theoretical -- whoever owns all the integrations (currently nobody) should be the shot-caller.

**Comment by vontell** [comment]
Closing since protos have now been removed
